Repository clubgamma/Internet-Speed-Tester, pull requests merged in 2024-10, with the labels that each got.

#9 Location And IP Address correctly displayed with icons
  .vscode/settings.json
  index.js
  package-lock.json
  package.json
  views/index.ejs
Labels: Level 1, hacktoberfest-accepted

#11 Fixed Security vulnerabilities and added .gitignore
  .gitignore
  index.js
  package-lock.json
  package.json
Labels: Level 1, hacktoberfest-accepted

#14 Added loading spinner
  views/index.ejs
Labels: Level 1, hacktoberfest-accepted

#18 Provide Fallback UI in Case of Errors
  views/index.ejs
Labels: Hacktoberfest2024, Level 1

#19 Vite+React
  .gitignore
  client/.gitignore
  client/README.md
  client/eslint.config.js
  client/index.html
  client/package-lock.json
  client/package.json
  client/public/favicon.ico
  client/public/logo192.png
  client/public/logo512.png
  client/public/manifest.json
  client/public/robots.txt
  client/public/vite.svg
  client/speed.env
  client/speeed.env
  client/src/App.jsx
  client/src/main.jsx
  client/vite.config.js
  package-lock.json
  package.json
  views/index.ejs
Labels: Level 1, hacktoberfest-accepted

#21 Revert "Mobile-First UI/UX Enhancements"
  client/index.html
  client/package-lock.json
  client/package.json
  client/src/App.css
  client/src/App.jsx
  server/package-lock.json
Labels: Level 3, hacktoberfest-accepted

#22 Mit
  client/index.html
  client/package-lock.json
  client/package.json
  client/postcss.config.js
  client/src/App.jsx
  client/src/index.css
  client/tailwind.config.js
Labels: Level 2, hacktoberfest-accepted

#24 Mit
  client/package-lock.json
  client/package.json
  client/src/App.jsx
Labels: Level 2, hacktoberfest-accepted

#26 Theme added and minor style changes
  client/package-lock.json
  client/package.json
  client/src/App.jsx
  client/src/index.css
Labels: Level 2, hacktoberfest-accepted

#30 Switch-to-client-measurement.
  client/.gitignore
  client/src/components/speedtest/SpeedDisplay.jsx
  client/src/components/speedtest/SpeedTest.jsx
  client/src/components/speedtest/TestButton.jsx
  client/src/utils/speedTestUtils.js
  server/.gitignore
  server/index.js
  server/package.json
Labels: Level 2, hacktoberfest-accepted

#34 Speed Test Visualization
  .env
  client/package.json
  client/src/components/SpeedTest/SpeedTest.jsx
  client/src/components/SpeedTest/TestButton.jsx
  client/src/components/speedtest/SpeedTest.jsx
  client/src/components/speedtest/TestButton.jsx
  postcss.config.js
  tailwind.config.js
Labels: Level 2, hacktoberfest-accepted

#39 Fixed upload speed
  .env.production
  client/src/utils/speedTestUtils.js
  example.env
  server/index.js
Labels: Level 1, hacktoberfest-accepted
